# Generated by Django 5.1 on 2024-08-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_life_product_mfd_product_stock_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='life',
            field=models.CharField(blank=True, default='10 days', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.CharField(blank=True, default='8', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default='koton', max_length=100, null=True),
        ),
    ]
