# Generated by Django 5.1 on 2024-09-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vendor_cover_image_alter_product_specifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Vendor',
            new_name='vendor',
        ),
    ]
