# Generated by Django 5.1 on 2024-09-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_vendor_product_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='title',
        ),
    ]
