# Generated by Django 5.1 on 2024-09-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='core.coupon'),
        ),
    ]
