# Generated by Django 5.1 on 2024-09-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cartorder_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('Shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=30, null=True),
        ),
    ]
